### ISSUE TITLE
Miners don't eat while mining

### ISSUE THREAD

**Issue by BarionLP** [remmintan/minefortress#32]
**Describe the bug**
(I just played around for the first time, so maybe I'm missing somehting)
My miner does not eat while mining in a mining zone and instead starts complaining. The only way to get him to eat is to remove the mining zone, wait for him to eat and then recreate it.

**To Reproduce**
Steps or conditions to reproduce the behavior:
1. Hire a miner
2. create a mining zone
3. wait for miner to get hungry
3. miner will not eat despite food being available

**Screenshots**

**Environment info:**
 - OS: Windows
 - Minecraft version: 1.20.2
 - Mod Version 1.12.1-beta

**Any other mods that you use**
none

**Comment by Eminence5070** [comment]
can confirm

**Comment by BarionLP** [comment]
can confirm fix with version 1.13.0-beta
